db:
  image: postgres
  ports:
    - "5434:5432"
another-fitness:
  build: .
  volumes:
    - ../:/code
    - .:/docker
  dockerfile: Dockerfile
  ports:
    - "8009:8000"
  links:
    - db
  hostname: docker