# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('repetition', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
