# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
